# Generated by Django 5.1.1 on 2024-10-03 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'verbose_name': 'Блог', 'verbose_name_plural': 'Блоги'},
        ),
    ]
