# Generated by Django 5.1.1 on 2024-09-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_descr_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='descr',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
